from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import spacy
spacy.load('en_core_web_sm')
# from spacy.lang.en import English
from chatterbot.trainers import ChatterBotCorpusTrainer

# Creating ChatBot Instance
chatbot = ChatBot('GecianBot')

# nlp = spacy.load("en_core_web_sm")

chatbot = ChatBot(
    'ChatBot for College Enquiry',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'I am sorry, but I do not understand. I am still learning.',
            'maximum_similarity_threshold': 0.90
        }
    ],
    database_uri='sqlite:///database.sqlite3'   
) 
trainer = ListTrainer(chatbot)

# python app.py
# Training with Personal Ques & Ans 
conversation = [
    "Hello",
    "Hi Human",
    "How are you doing ?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome.",
    "what is your name ?" ,
    "I'm GecianBot",
    "who made you ?",
    "I created by Kumavat Vijay (kvm3)",
    "1",
    "<b style='color:red'>1. Student Section Enquiry : </b><pre style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.1  Bonafide Certificate<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.2  Remedial Exam<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.3  Admission process<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.4  Scholarship<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.5 TFWS<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6 Important website</pre>",
    "1.1",
    "<b style='color:red'>1.1 bonafide Certificate : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Go to the student stesnory.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Celect the bonafide and fill up <a href=""static/document/APPLICATION_BONAFIED_CERTIFICATE.pdf"">(Check the bonafide form).</a></h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Take your coordinator sign.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Go to student section (ADM building) and take the symbol of gecbhavnagar with i-card and one passport-side photo.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">Then, Your bonafide certificate is done😉.</h6>",
    "1.2",
    "<b style='color:red'>1.2 Remedial Exam : </b><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ First of all, fill up and print the gtu remedial from.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Go to the Student section (ADM building).</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Give the remedial from and some remedial amount (per subject 250 ₹).</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Fill the remedial from online Guideline 👇🏻</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Guidess of remedial from : <a href="'static/document/Examform_student_guide_Remedial.pdf'">Guide_Remedial.pdf</a></h6>",
    "1.3",
    "<b style='color:red'>1.3 Admission process : </b><pre style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.1 Admission seats<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.2 Application process<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.3 Reservation<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.4 Fees & Eligibility<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.5 Ratting & Reviews<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.6.6 <a href='http://gtu-info.com/D2D-Engineering-Admission'></a>D2D Admission process<br><br>▪️ GEC Bhavnagar offers B.E degree course in 6 specializations.</b><br>▪️ Admission to B.E course is done on the basis of Gujarat Common Entrance Test (GUJCET) conducted by Gujarat Secondary and Higher Secondary Education Board (GSEB).<br>▪️ Candidates should have passed 10+2 in Science stream in order to be eligible for GUJCET.<br>▪️ Admissions are provided on the basis of merit list, prepared by considering the candidates’ performance in the qualifying exam and GUJCET.<br>▪️ Application forms for GUJCET are filled online.<br><br><img src=""static/images/a_proc.jpg"" alt=""Admission process"" width="'933'" height="'319'"></pre>",
    "1.3.1",
    "<b style='color:red'>1.3.1 Admission seats : </b><br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Government College of Engineering, Bhavnagar offers B.E in 6 specializations. The basic eligibility criteria for admission to BE degree course is 10+2 in Science stream with at least 45% marks.<br>▪️ Candidates are selected on the basis of GUJCET/JEE Main score. The admission shall be granted on the basis of merit list which is prepared by taking into account 60% marks in theory subjects of Physics, Chemistry, Mathematics in 10+2 and 40% marks of GUJCET entrance test.<br>▪️ Those with a valid JEE Main score are exempted from GUJCET.<br><br><img src=""static/images/a_seat.jpg"" alt=""Admission seats"" width="'1323'" height="'361'"><br><br><b>Key points for B.E admission :</b>▪️ Candidates appearing in JEE need not appear for GUJCET.<br>▪️ 5% relaxation for SC/ST candidates in qualifying exam criteria.<br>▪️ 50% seats are filled by candidates having a valid JEE Main score.<br>▪️ JEE Main counseling is done by JoSAA Joint Seat Allocation Authority (JoSAA).<br></pre>",
    "1.3.2",
    "<b style='color:red'>1.3.2 Application process : </b><br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Application form for GUJCET can be accessed by first submitting Demand Draft of Rs 300/- as application fee at help centers to get User ID.<br>▪️ After getting this User ID candidates can then fill application forms by logging onto website.<br>▪️ Documents required to be uploaded by the applicants as per the specifications required are :<br>       - A recent passport size photograph with specifications: 5Kb-50Kb and format of photograph should be JPG or JPEG.<br>        - Candidate’s Signature</pre>",
    "1.3.3",
    "<b style='color:red'>1.3.3 Reservation : </b><br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>Reservations for various categories are as follows :</b><br>▪️ No caste certificate shall be valid unless it is duly stamped, signed and issued by the any authority which has been empowered by the Government of Gujarat.<br><br><img src=""static/images/a_rese.png"" alt=""Reservation"" width="'1132'" height="'282'"></pre>",   
    "1.3.4",
    "<b style='color:red'>1.3.4 Fees & Eligibility : </b><br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>▪️ Fees : </b>₹1,500 (1st Year Fees)<br><b>▪️ ELIGIBILITY : </b>10+2 with 45% + GUJCET</pre>",
    "1.3.5",
    "<b style='color:red'>1.3.5 Ratting & Reviews : </b><br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><img src=""static/images/a_ratt.png"" alt=""Ratting & Reviews"" width="'1317'" height="'236'"></pre>",
    "1.4",
    "<b style='color:red'>1.4 Scholarship offical sites : </b><br><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'https://mysy.guj.nic.in/'">▪️ MYSY - Mukhyamantri Yuva Swavalamban Yojana</a><br><a href="'https://www.digitalgujarat.gov.in/loginapp/CitizenLogin.aspx'">▪️ Digital Gujarat</a></h6><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>DOCUMENTS REQUIRED (SELF ATTESTED) :</b><br>▪️ Aadhaar Card Xerox<br>▪️ 10th Std. / 12th Std Marksheet Xerox (whichever is applicable)<br>▪️ Admission Letter given by Admission Committee<br>▪️ Fee Receipt<br>▪️ Self Decleration (Original)<br>▪️ College Principal's certificate in College Letterhead<br>▪️ Parent's Annual Income Certificate (Given by TDO or Mamlatdar)<br>▪️ Bank Account Proof (Nationalize Bank Account Passbook's first page Xerox)<br>▪️ Hostel Admission Letter and Fee Receipt<br>▪️ Affidavit Original (Non-Judicial stamp paper of Rs. 20/)<br><br><b>Important Links for MYSY :</b><br><a href="'http://gtu-info.com/MYSY-Scholarship-Mukhyamantri-Yuva-Swavalamban-Yojana-registration#gallery-1'">▪️ Gtu eligility</a><br><a href="'http://gtu-info.com/MYSY-Scholarship-Mukhyamantri-Yuva-Swavalamban-Yojana-registration#gallery-3'">▪️ Scholarship Amount</a><a href="'http://gtu-info.com/MYSY-Scholarship-Mukhyamantri-Yuva-Swavalamban-Yojana-registration#gallery-4'">▪️ Gtu intructions</a><br><a href="'https://mysy.guj.nic.in/Noticeboard/MYSY%20Courses%20List2%20Aug16.pdf'">▪️ Course list under mysy scholarship</a><br><a href="'https://mysy.guj.nic.in/Frm_stu_tot_rej.aspx'">▪️ Help center list</a><br><a href="'https://mysy.guj.nic.in/Noticeboard/Affidavit%20for%20MYSY.pdf'">▪️ Affidavit format</a><br><a href="'https://mysy.guj.nic.in/Noticeboard/Sample%20Income_Certificate.pdf'">▪️ Income certificate format</a><br><a href="'https://mysy.guj.nic.in/Noticeboard/certificate%20from%20Inst.pdf'">▪️ Renewal application certificate</a></pre>",
    "1.5",
    "<b style='color:red'>1.5 TFWS : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>What is TFWS? OR Benefits of TFWS : </b><br>▪️ If student got admission under TFW scheme then students do not have to pay tuition fee but students have to pay other fee such as exam fee, bus fee, deposit and hostel fee.<br><br><b>SEATS RESERVED FOR TFWS : </b><br>▪️ 5% of total seats shall be filled by TFW scheme.<br>▪️ Example: If there are 120 students in a department then there will be 6 Supernumerary Seats (in addition to 120 seats)<br><br><b>ELIGIBILITY FOR TFWS :</b><br>▪️ Students whose parent's income is less than Rs. 8 lakh/annum are eligible for TFWS.<br>▪️ To get the benefits of TFW Scheme, the candidate has to submit the income certificate issued after 31st March from either 'Mamlatdar' or 'Taluka Development Officer (TDO)' or 'Collector(Jan Seva Kendra)' at the time of application form filling (registration for admission).<br>▪️ No other document shall be considered valid(e.g. Income tax return, Certificate issued by 'Sarpanch').<br><br><b>INSTRUCTIONS :</b><br>▪️ Students admitted under this scheme shall not be allowed to change Institution/course under any circumstances.<br>▪️ Admission is strictly on merit number through admission committee.<br>▪️ TFW scheme shall be applicable for complete duration of the course (4 Years).<br>▪️ Candidates who want to opt for these additional TFWS seats will have to specify their willingness in the option form as a separate choice code.<br>▪️ In the event of non-availability of students in this category the same shall not be given to any other category of applicants.</h6>",
    "1.6",
    "<b style='color:red'>1.6 Important website : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>☛ <a href="'https://www.gtu.ac.in/'">GTU Offical</a><br>☛ <a href="'http://gtu-info.com/'">GTU Info</a><br>☛ <a href="'http://gtu-info.com/GTU-Exam-Time-Table'">Exam Time-Table</a><br>☛ <a href="'http://www.gecbh.cteguj.in/'">Gec Bhavnagar Offical</a><br>☛ <a href="'http://gtu-info.com/college/GEC-Bhavnagar/GEC-Bhavnagar'">Gec Bhavnagar-Gtu</a><br>☛ <a href="'http://www.jacpcldce.ac.in/'">ACPC</a><br>☛ <a href="'https://www.gtu.ac.in/result.aspx'">GTU result</a><br></h6>",
    # <br><img src=""static/images/tp_place.png"" alt=""Placement_Team"" width="'1205'" height="'590'">
    # ▪️ 
    # ----------------# "2.2 Time Table of CED : You can ask this Question to your Class CR and your class Coordinator",
    # "",
    # "<b style='color:red'>2. Computer Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.1  - Semester wise Subject.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.2  - Facultys.</h6>",
    # "",
    # "<b style='color:red'> - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'static/images/sem1-2.png'">▪️ Semester 1-2</a><br><a href="'static/images/ce_sem3.png'">▪️ Semester 3</a><br><a href="'static/images/ce_sem4.png'">▪️ Semester 4</a><br><a href="'static/images/ce_sem5.png'">▪️ Semester 5</a><br><a href="'static/images/ce_sem6.png'">▪️ Semester 6</a><br><a href="'static/images/ce_sem7.png'">▪️ Semester 7</a><br><a href="'static/images/ce_sem8.png'">▪️ Semester 8</a></pre>",
    # "",
    # "<b style='color:red'> - Facultys : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://www.gecbh.cteguj.in/facultydetail/show/37745'">▪️ MR. KARSHAN KANDORIYA (HOD)</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/37765'">▪️ MR. ASHISH NIMAVAT</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38920'">▪️ MR. CHINMAY VYAS</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38921'">▪️ MISS. HARDI SANGHAVI</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38922'">▪️ MISS. SAHISTABANU MACHCHHAR</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38923'">▪️ MR. KAMLESH MAKVANA</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38925'">▪️ MR. KIRIT RATHOD</a><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38924'">▪️ MR. VISHAL ANDODARIYA</a><br><a href="'http://www.gecbh.cteguj.in/facultydetail/show/38927'">▪️ MISS. URVASHI SOLANKI</a></pre>",

    "2",
    "<b style='color:red'>2. Computer Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.1 CE - Subjects and Syllabus.</h6>",
    "2.1",
    "<b style='color:red'>CE - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://gtu-info.com/Branch/Computer-Engineering/Syllabus'">▪️ Semester 1-8</a></pre>",
    "3",
    "<b style='color:red'>3. IT Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.1 IT - Subjects and Syllabus.</h6>",
    "3.1",
    "<b style='color:red'>IT - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://gtu-info.com/Branch/IT-Information-Technology/Syllabus'">▪️ Semester 1-8</a></pre>",
    "4",
    "<b style='color:red'>4. Mech Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4.1 Mech - Subjects and Syllabus.</h6>",
    "4.1",
    "<b style='color:red'>Mech - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://gtu-info.com/Branch/Mechanical-Engineering/Syllabus'">▪️ Semester 1-8</a></pre>",
    "5",
    "<b style='color:red'>5. Civil Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.1  - Semester wise Subject.</h6>",
    "5.1",
    "<b style='color:red'>Civil - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://gtu-info.com/Branch/Civil-Engineering/Syllabus'">▪️ Semester 1-8</a></pre>",
    "6",
    "<b style='color:red'>6. EC Engineering Enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.1  - Semester wise Subject.</h6>",
    "6.1",
    "<b style='color:red'>EC - Subjects and Syllabus : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><a href="'http://gtu-info.com/Branch/EC-Engineering/Syllabus'">▪️ Semester 1-8</a></pre>",
    "7",
    "<b style='color:red'>7. College Section Enquiry : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>7.1 About the GEC Bhavnagar <br>7.2 Info of GEC Bhavanagar<br>7.3 Contact of GEC Bhavnagar<br>7.4 About Training & Placement Cell<br>7.5 Faculty<br>7.6 GTU - College News <br>7.7 Social links</pre>",
    "7.1",
    "<b style='color:red'>7.1 About the GEC Bhavnagar<a href="'static/cett.jpeg'"></a> : </b><br><h6 style='font-size: 13px;text-align: justify;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The institute is having huge newly constructed buildings and separate blocks for E.C Department, Mechanical and Production, Library Building, Amenity Building, Works Shop and Administrative Building. Government engineering college,Bhavnagar has always been active in improving the library facility.It offers its services to about 1000 students of different branches of engineering and faculty and staff from various departments of the institute and neighboring institution.The institute is spread over 43400 meter square of land area with 14300 square meters of land having huge newly constructed buildings and separate blocks for Electronics and Communication Department, Mechanical and Production Department, Library Building, Amenity Building, Works Shop and Administrative Building.</h6>", 
    "7.2",
    "<b style='color:red'>7.2 Info of GEC Bhavanagar : </b><h6 style='font-size:13px'><br>GTU Code : 021 <br> Estd. Year : 2008 <br> Fees (2020) : ₹ 1,500 <br> College Type : Government <br> Affiliated To : GTU <br> Distance : 4.9 KM From Bhavnagar <br> Hostel : Yes <br> Transportation : No <br><a href='https://www.google.com/maps/place/Government+Engineering+College,+Bhavnagar/@21.7598519,72.1304915,17z/data=!3m1!4b1!4m5!3m4!1s0x395f508526704e0d:0xfd6803c3cfa8bf82!8m2!3d21.7598519!4d72.1326802'>Gec Bhavnagar Map</a></h6>",
    "7.3",
    "<b style='color:red'>7.3 Contact of GEC Bhavnagar : </b><h6 style='font-size:13px'> <br> Phone : <a href=""tel:+0278-2525354"">+0278-2525354</a> ,<a href=""tel:+0278-2513251"">+0278-2513251</a><br> Fax : 0278-2525354 <br> Email : <a href=""mailto:gec-bhav-dte@gujarat.gov.in"">gec-bhav-dte@gujarat.gov.in</a><br> Website : <font color=blue><a href=""http://www.gecbh.cteguj.in"">GEC-Bhavnagar</a></font><br> Address : Government Engineering College, Nr. BPTI, Vidhyanagar, Bhavnagar - 364002 <br> City : Bhavnagar</h6>",
    "7.4",
    "<b style='color:red'>7.4 About Training & Placement Cell : </b><br><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ The purpose of the  Training and Placement Cell at GEC, Bhavnagar , is to guide students to choose right career and to give knowledge, skill and aptitude and meet the manpower requirements of the Industry.<br>▪️ The Training and Placement Cell of GEC Bhavnagar is facilitated by Training and Placement Officer as head and the Departmental Training and Placement Officers as coordinators. Student representatives from each department are assisting in overall coordination of the activities.</h6><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>Career Guidance : </b><br>▪️ Highlighting articles on departmental notice boards regarding Competitive & Industrial Career Opportunities.<br>▪️ Inform students about the available job opportunities in government sectors and off campus drives.<br>▪️ Giving Motivational Talks.<br>▪️ Conducting Psychometric Test.<br>▪️ Conducting Expectation Management Workshops</pre><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><b>Training & Development :</b><br>Keeping in view the industry requirements, TP Cell helps students to be prepared to work as entry level Graduate Engineer Trainees. Following activates are planned for students to sharpen their skills and abilities.<br>▪️ Personality Development<br>▪️  Communication Skills & Vocabulary<br>▪️ Resume Preparation& Email Writing<br>▪️ Group Discussion<br>▪️  Interview Skills<br>▪️ Aptitude Training & Practice Tests<br><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><img src=""static/images/tp_place.png"" alt=""Placement_Team"" width="'1205'" height="'590'"></pre><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Many companys is come for placement in our gec bhavnagar college (some 2020 companys👇🏻 and approximately 25-35 companies are come in gecb) :</h6><br><pre><img src=""static/images/place_company.jpeg"" alt=""Placement_campany"" width="'322'" height="'402'"></pre>",
    "7.5",
    "<b style='color:red'>7.5 Faculty : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><b><br>Numbers of faculty</b><br><br>▪️ In Civil : 5<br>▪️ In Computer : 9<br>▪️ In EC : 16<br>▪️ In IT : 8<br>▪️ In Mechanical : 24<br>▪️ In Production : 13<br>▪️ In General : 10<br>▪️ Total faculty : 85<br><a href="'http://www.gecbh.cteguj.in/faculty/'">▪️ GEC Bhavnagar facultys</a><br><br>Note : The facultys are changeable in every year.So, we can not provide all details.</pre>",
    "7.6",
    "<b style='color:red'>7.6 GTU - College News : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>☛ <a href="'http://www.gecbh.cteguj.in/news'">News</a><br><br>Note : The news is every month is changeable. So, we can not provide.</h6>",
    "7.7",
    "<b style='color:red'>7.7 Social links : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>▪️ <a href="'https://www.instagram.com/gecbhavnagar/'">Instagram <img src="'https://img.icons8.com/fluent/48/000000/instagram-new.png'" width="'15'" height="'15'"/></a><br>▪️ <a href="'https://www.facebook.com/Gecbhavn/'">Facebook <img src="'https://img.icons8.com/fluent/48/000000/facebook-new.png'" width="'15'" height="'15'"/></a><br>▪️ <a href="'https://twitter.com/gecbvnignite'">Twitter <img src="'https://img.icons8.com/fluent/48/000000/twitter.png'" width="'15'" height="'15'"/></a><br>▪️ <a href="'https://www.linkedin.com/school/gecbhavnagar/'">Linkedin<img src="'https://img.icons8.com/fluent/48/000000/linkedin.png'" width="'15'" height="'15'"/></a><br>▪️ <a href="'https://www.youtube.com/channel/UC97GsoAAxFoTN2pArFH2lRQ'">Youtube<img src="'https://img.icons8.com/fluent/48/000000/youtube-play.png'" width="'15'" height="'15'"/></a><br><br>Go to our social links and watch the activity😉.</h6>",
    "8",
    "<b style='color:red'>8. College Section Enquiry : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>8.1  100 Activity point  <br>8.2 GTU - Attendance Rule<br>8.3 Detention Rule</pre>",
    "8.1",
    "<b style='color:red'>8.1  100 Activity point : </b><br><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Gujarat Technological University (GTU) will implement the evaluation system in 100 – Activity Points that has already been launched in the beginning of the current Academic Year i.e. 2015-16 for earning the GTU’s Engineering Degree. Any B.E. Student of GTU will be honoured the B.E. Degree once s/he earns the Minimum 100 Activity Points during his total academic tenure. The points student has earned are reflected in the student’s transcript.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br><br><b>Detail about the evaluation system</b><br>▪️ There will be unique registration no. with enrolment_no., E-mail for the same will be registered by the student. The claim/s from the student will be reviewed by internal evaluator as a teacher, HOD or Principal at the primary level on the monthly basis. Viva will be conducted to validate the students about their work and earned Activity Points. Internal evaluator will physically collect the data, cross question the student and verify the student’s claim.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br><b>Benefits from the 100-points</b><br><br>▪️ Globally, engineering education systems have continuously evolved, in order to address the needs of the industry and the society. Industry needs professionals who can work successfully in teams, who have leadership qualities, who are alive to social and community needs and who can bring innovation and creativity to their work. Hence, in order to prepare its students to match these multifarious requirements, GTU has created the unique mechanism. GTU will be able to reap benefits from these activities at their own pace and comfort. It is expected that by the time GTU’s students reach their Final Year, they would have developed themselves so well both through their studies in the respective technological field and through their active participation in the co-curricular and extra-curricular activities that they would be well-prepared for contributing to building the India and the world of their dreams.</h6><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br><b>Weightage to Bridge course</b><br><br>▪️ Bridge course will be done before first year practical exam. Every year the students with their chosen subjects will be registered. 8 points out of 100 are specially allocated to Bridge course only. At the end of semester 2, a student can start any activity except Bridge course. As semester 1 is 15 days longer, 7 days are given for village visit. Bridge course evaluation at the end of semester 1 for not only documentation verification but the viva questions will be such that the authority of work is done or not is checked. Similarly, all evaluations will be conducted in semester 2, 4, 6 & 8.</h6>",
    "8.2",
    "<b style='color:red'>8.2 GTU - Attendance Rule : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>▪️ Minimum 75% attendance is must to fill GTU Examnination form and to appear in End (Final) Semester or External Examniation.<br>▪️  10% of total absentia of students due to illness may be consider by Institute. (Circular No: GTU/Circular/M.L./2011/2763 Date: 02-04-2011).<br>▪️ Example: If you are absent for 30 days due to illness then present of only 3 days will be considered.<br><a href="'http://old.gtu.ac.in/circulars/11Apr/circular020411.pdf'">▪️ GTU Attendance Rule</a><br><br><b>Online Attendance System</b><br>▪️ Online attendance system software is under updating process till that all are informed to maintain attendance record at the institute level / branch wise / subject wise / enrollment no. wise. Once link is available on GTU website, institute will be required to upload attendance report on GTU web portal.<br><a href='http://old.gtu.ac.in/circulars/13Jul/Online_Attendance_%20System.pdf'>▪️ Online Attendance System</a></h6>",
    "8.3",
    "<b style='color:red'>8.3 Detention Rule : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>▪️ Above norms of Detention for all the courses for GTU students is applicable for the students admitted in Academic year 2018-19 onwards.<br>▪️ For B. Arch. course the rules for passing as mentioned in circular no. GTU/ACAD/B.Arch./689 dated 21.01.2014 and circular no. GTU/Academic/2016/9851 dated 28.12.2016 will also be applicable.<br>▪️ <a href="'https://s3-ap-southeast-1.amazonaws.com/gtusitecirculars/uploads/Circular_New_Norms_For_admission_332353.pdf'">Circular for detention</a><br><br>Note : All the students who are having backlog more than 4 excluding immediate previous semester backlog are not eligible for continuing of study till he/she fulfills eligibility criteria.<br><br><b>Explanation : </b><br>▪️ At any point of time, student can have maximum 4 backlogs (FF) pending.<br>▪️ If backlogs are more than 4 than new subjects will not be allocated and he\she is detained for one year.<br>▪️ Immediate previous semester backlogs are not counted for detain purpose.<br><a href='static/images/dete.png' width="'1375'" height="'457'"></a></h6>",
    "9",
    "<b style='color:red'>9 Other enquiry : </b><br><pre style="'font-family:Helvetica,sans-serif;font-size:13px'"><br>9.1 Complaint form <br>9.2 Parking Enquiry<br>9.3 Hostel Enquiry.</pre>",
    "9.1",
    "<b style='color:red'>9.1 Complaint form : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ Go to the stesnory, take the complaint form and fill the your complaint and drop the complaint form in complaint box.</h6>",
    "9.2",
    "<b style='color:red'>9.2 Parking enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">▪️ The parking area is big in our college and more then student are available in our colloge.So, some time park the any vehicales are complicated. So, that why you can only listen to security guad.But sometime you have any problem so tell him security guad.</h6>",
    "9.3",
    "<b style='color:red'>9.3 Hostel enquiry : </b><br><h6 style="'font-family:Helvetica,sans-serif;font-size:13px'">Our college have boys and girls hostel are available.you can join this hostel.so first of all you go to workshop and take the hostel form and fill the form then after wait for cutoff.While cutoff are available and your name is there so you can add our hostel otherwise you should have another option.</h6>",
]

trainer.train(conversation)
